---
- hosts: exemplo
  remote_user: gustavoa
  become: yes
  tasks:
    - name: "Executar o container MySQL"
      docker_container:
        name: banco
        image: mysql:5.6
        env:
          MYSQL_ROOT_PASSWORD: senha123
    - name: "Executar o container Wordpress"
      docker_container:
        name: wordpress
        image: wordpress
        links:
          - "banco:mysql"
        ports:
          - "80:80"
